services:
  #  eureka-server:
  #    image: ghcr.io/cfranzen/microservices-playground/eureka-server:latest
  #    container_name: eureka-server
  #    ports:
  #      - "127.0.0.1:8761:8761"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - app
  #    depends_on:
  #      - zipkin
  #
  #  apigw:
  #    image: ghcr.io/cfranzen/microservices-playground/apigw:latest
  #    container_name: apigw
  #    ports:
  #      - "127.0.0.1:8083:8083"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - app
  #    depends_on:
  #      - zipkin
  #      - eureka-server

  customer:
    image: ghcr.io/cfranzen/microservices-playground/customer:latest
    container_name: customer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

  fraud:
    image: ghcr.io/cfranzen/microservices-playground/fraud:latest
    container_name: fraud
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

  notification:
    image: ghcr.io/cfranzen/microservices-playground/notification:latest
    container_name: notification
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  postgres:
  pgadmin: