services:
  customer:
    image: ghcr.io/cfranzen/microservices-playground/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

  #  customer2:
  #    image: ghcr.io/cfranzen/microservices-playground/customer:latest
  #    container_name: customer2
  #    ports:
  #      - "9080:8080"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - app

  fraud:
    image: ghcr.io/cfranzen/microservices-playground/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

  notification:
    image: ghcr.io/cfranzen/microservices-playground/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

  apigw:
    image: ghcr.io/cfranzen/microservices-playground/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app
    depends_on:
      - customer
      - fraud

  fraud-learning:
    image: ghcr.io/cfranzen/microservices-playground/fraud-learning:latest
    container_name: fraud-learning
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app

networks:
  app:
    driver: bridge