server:
  port: 8082

spring:
  application:
    name: notification
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://config-server:8888
  data:
    mongodb:
      host: 'localhost'
      database: 'notification'
      username: 'notification'
      password: 'notification'

eureka:
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

logging:
  config: classpath:logback-graylog.xml