server:
  port: 8082

spring:
  application:
    name: notification
  data:
    mongodb:
      host: 'localhost'
      database: 'notification'
      username: 'notification'
      password: 'notification'
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key

logging:
  config: classpath:logback-graylog.xml