server:
  port: 8083

spring:
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://config-server:8888
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: fraud
          uri: lb://FRAUD
          predicates:
            - Path=/api/v1/fraud/**

eureka:
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

logging:
  config: classpath:logback-graylog.xml