spring:
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    url: jdbc:postgresql://postgres:5432/fraud
  redis:
    host: redis

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  graylog:
    host: graylog