server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'microservices'
    password: 'microservices'
    url: jdbc:postgresql://localhost:5051/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411
  redis:
    host: localhost
    port: 6379
    timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

logging:
  config: classpath:logback-graylog.xml