spring:
  zipkin:
    base-url: http://localhost:9411
  kafka:
    producer:
      bootstrap-servers: localhost:9093
    consumer:
      bootstrap-servers: localhost:9093
  rabbitmq:
    addresses: localhost:5672

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka