server:
  port: 8084

spring:
  application:
    name: fraud-learning
  zipkin:
    base-url: http://localhost:9411
  kafka:
    consumer:
      bootstrap-servers: localhost:9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

logging:
  config: classpath:logback-graylog.xml