spring:
  zipkin:
    base-url: http://zipkin:9411
  kafka:
    consumer:
      bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  graylog:
    host: graylog