server:
  port: 8084

spring:
  application:
    name: fraud-learning
  config:
    import: configserver:http://localhost:8888
    
eureka:
  instance:
    metadataMap:
      metrics.path: "/actuator/prometheus"

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: 'always'

logging:
  config: classpath:logback-graylog.xml